### ISSUE TITLE
Maquetación de homepage

### ISSUE THREAD

**Issue by RodrigoScott** [RodrigoScott/stefanini-app#2]
## Task

- [ ] Crear maqueta de homePage para recibir data dummy en base a petición de tarea
- [ ] Crear widget de card para mostrar información
- [ ] Para el precio en caso de ser menor a 0.5 mostrar el texto FREE.
- [ ] Crear listview para permitir scroll a la pantalla
- [ ] Crear grid para mostrar solo 2 objetos por fila para pantallas verticales

![Captura de pantalla 2023-06-26 a la(s) 20 47 57](https://github.com/RodrigoScott/stefanini-app/assets/25831861/2039cb56-6bc1-4891-a9c2-2b7ec438fbf4)
