### ISSUE TITLE
Llenado de información de homepage

### ISSUE THREAD

**Issue by RodrigoScott** [RodrigoScott/stefanini-app#3]
## task 

- [x] Almacenar imágenes de forma local
- [x] Crear modelo para crear lista de objetos 
- [x] Agregar valores de modelo app: Nombre, desarrollador, categoría, calificación, costo, descripción, avatar, imagenL, instalado, comentarios de usuarios
- [x] Agregar modelo de usuarios para comentarios de modelo app: usuario, avatar, comentario
