### ISSUE TITLE
Pantalla de detalles

### ISSUE THREAD

**Issue by RodrigoScott** [RodrigoScott/stefanini-app#4]
## task

- [ ] Implementar hero tag para animación a pantalla de detalles en base a imagen 
- [ ] Crear pantalla para mostrar detalles de objeto
- [ ] Implementar flutter_rating_bar para ranqueo de objeto
- [ ] Las estrellas deberán de estar en color verde si son tres o más y en color rojo en caso de tener dos o menos.
- [ ] El botón instalar únicamente se deberá visualizar si el atributo instalado está en false para cada aplicación respectiva. Dicho botón no tendrá funcionalidad alguna.
- [ ] En la ventana modal también deberá visualizarse las imágenes que son screenshots de ejemplo, las url de estas imágenes está en un atributo del mismo nombre para cada aplicación.
